
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: backend-domain
  description: Domain for all backend-related systems
spec:
  owner: backend-team

---

apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: core-platform
  description: Main backend system containing user and payment services
spec:
  owner: backend-team
  domain: backend-domain

---

apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: postgres-user-db
  description: PostgreSQL database for user-service
spec:
  type: database
  owner: backend-team
  system: core-platform

---

apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: postgres-payment-db
  description: PostgreSQL database for payment-service
spec:
  type: database
  owner: backend-team
  system: core-platform

---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: user-api
  description: API for user-related operations
spec:
  type: openapi
  lifecycle: production
  owner: backend-team
  definition: |
    openapi: 3.0.0
    info:
      title: User API
      version: 1.0.0
    paths:
      /users:
        get:
          summary: List users
          responses:
            "200":
              description: OK

---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: payment-api
  description: API for payment and transaction operations
spec:
  type: openapi
  lifecycle: production
  owner: backend-team
  definition: |
    openapi: 3.0.0
    info:
      title: Payment API
      version: 1.0.0
    paths:
      /payments:
        post:
          summary: Create a payment
          responses:
            "201":
              description: Created

---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: email-api
  description: External email notification service (mocked for demo)
spec:
  type: openapi
  lifecycle: production
  owner: external-partner
  definition: |
    openapi: 3.0.0
    info:
      title: Email API
      version: 1.0.0
    paths:
      /send:
        post:
          summary: Send an email
          responses:
            "200":
              description: Sent

---

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: user-service
  description: Handles user authentication and profile management
  tags:
    - go
    - grpc
spec:
  type: service
  lifecycle: production
  owner: backend-team
  system: core-platform
  providesApis:
    - user-api
  consumesApis:
    - email-api
  dependsOn:
    - resource:postgres-user-db

---

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: payment-service
  description: Manages payment processing and transactions
  tags:
    - python
    - fastapi
spec:
  type: service
  lifecycle: production
  owner: backend-team
  system: core-platform
  providesApis:
    - payment-api
  consumesApis:
    - user-api
  dependsOn:
    - resource:postgres-payment-db

---

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backend-pipeline
  description: CI/CD pipeline for backend services
spec:
  type: ci-pipeline
  lifecycle: production
  owner: backend-team
  dependsOn:
    - component:user-service
    - component:payment-service
