apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstagetest1
  description: An example service owned by the Platform Team
  owner: team-platform      # links to your group
spec:
  type: service             # could be service, website, library, API, etc.
  lifecycle: production     # or experimental, deprecated
  system: example-system    # optional: the system this component belongs to
  repository: https://github.com/bateternal/backstagetest1  # public GitHub repo