apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstagetest1
  description: A comprehensive Django application integrated with Backstage for demonstrating various documentation patterns and best practices
  annotations:
    github.com/project-slug: bateternal/backstagetest1
    backstage.io/source-location: url:https://github.com/bateternal/backstagetest1
    backstage.io/managed-by-location: url:https://github.com/bateternal/backstagetest1
    backstage.io/techdocs-ref: github:https://github.com/bateternal/backstagetest1/tree/main/docs
spec:
  type: service
  lifecycle: production

---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: backstagetest1-api-location
spec:
  type: url
  target: ./backstagetest1-api.yaml
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: backstage-catalog-api-location
spec:
  type: url
  target: ./backstage-catalog-api.yaml
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: backstage-database-location
spec:
  type: url
  target: ./backstage-database.yaml
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: backstage-cache-location
spec:
  type: url
  target: ./backstage-cache.yaml
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: backstage-demo-system-location
spec:
  type: url
  target: ./backstage-demo-system.yaml
