apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstagetest1
  annotations:
    github.com/project-slug: bateternal/backstagetest1
    backstage.io/techdocs-ref: value
spec:
  type: other
  lifecycle: unknown
  owner: team-platform
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-platform
  annotations:
    backstage.io/allowed-kinds: Component,User,Group
spec:
  type: team
  profile:
    displayName: Platform Team