apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstagetest1
  description: A comprehensive Django application integrated with Backstage for demonstrating various documentation patterns and best practices
  annotations:
    github.com/project-slug: bateternal/backstagetest1
    backstage.io/techdocs-ref: dir:./docs
    backstage.io/source-location: url:https://github.com/bateternal/backstagetest1
    backstage.io/managed-by-location: url:https://github.com/bateternal/backstagetest1
spec:
  type: service
  lifecycle: production
  owner: smarties
  system: backstage-demo
  providesApis:
    - backstagetest1-api
  consumesApis:
    - backstage-catalog-api
  dependsOn:
    - resource:backstage-database
      type: database
    - resource:backstage-cache
      type: cache